// implement SockNotifier
// andycai.sc@gmail.com 2013-03-18
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#include "NameSpaceDefine.h"
#include ADD_QUOTE(INC_NAME_HEADER(NAMESPACE_NAME, SockNotifier.h))
#include ADD_QUOTE(INC_NAME_HEADER(NAMESPACE_NAME, SockReactor.h))
#include ADD_QUOTE(INC_NAME_HEADER(NAMESPACE_NAME, SockNotification.h))

BEGIN_CXX_NAMESPACE_DEFINITION

SockNotifier::SockNotifier(const Poco::Net::Socket& socket):
	m_socket(socket)
{
}

SockNotifier::~SockNotifier()
{
}

void SockNotifier::addObserver(SockReactor* pReactor, const Poco::AbstractObserver& observer)
{
	m_notifiCenter.addObserver(observer);
	{
	    Poco::Mutex::ScopedLock locker(m_obsMutex);
	    m_observers.push_back(observer.clone());
	}

    resumeObserver(pReactor, observer);
}

void SockNotifier::removeObserver(SockReactor* pReactor, const Poco::AbstractObserver& observer)
{
	m_notifiCenter.removeObserver(observer);
	{
	    Poco::Mutex::ScopedLock lock(m_obsMutex);
        for (ObserverList::iterator it = m_observers.begin(); it != m_observers.end(); ++it)
        {
            if (observer.equals(**it))
            {
                m_observers.erase(it);
                break;
            }
        }
	}

	suspendObserver(pReactor, observer);
}

void SockNotifier::dispatch(SockNotification* pNotification)
{
	static Poco::Net::Socket nullSocket;

	Poco::AutoPtr<SockNotification> pNf = clone(pNotification);

	pNf->setSocket(m_socket);
	pNf->duplicate();
	try
	{
		m_notifiCenter.postNotification(pNf);
	}
	catch (...)
	{
		pNf->setSocket(nullSocket);
		throw;
	}
	pNf->setSocket(nullSocket);
}

bool SockNotifier::accepts(SockNotification* pNotification)
{
	return m_notifications.find(pNotification) != m_notifications.end();
}

void SockNotifier::suspendObserver(SockReactor* pReactor, const Poco::AbstractObserver& observer)
{
    std::multiset<SockNotification*>::iterator it = m_notifications.end();
    if (observer.accepts(pReactor->m_pReadableNotification))
		it = m_notifications.find(pReactor->m_pReadableNotification.get());
	else if (observer.accepts(pReactor->m_pWritableNotification))
		it = m_notifications.find(pReactor->m_pWritableNotification.get());
	else if (observer.accepts(pReactor->m_pErrorNotification))
		it = m_notifications.find(pReactor->m_pErrorNotification.get());
	else if (observer.accepts(pReactor->m_pTimeoutNotification))
		it = m_notifications.find(pReactor->m_pTimeoutNotification.get());
	if (it != m_notifications.end())
		m_notifications.erase(it);
}

void SockNotifier::resumeObserver(SockReactor* pReactor, const Poco::AbstractObserver& observer)
{
    if (observer.accepts(pReactor->m_pReadableNotification))
		m_notifications.insert(pReactor->m_pReadableNotification.get());
	else if (observer.accepts(pReactor->m_pWritableNotification))
		m_notifications.insert(pReactor->m_pWritableNotification.get());
	else if (observer.accepts(pReactor->m_pErrorNotification))
		m_notifications.insert(pReactor->m_pErrorNotification.get());
	else if (observer.accepts(pReactor->m_pTimeoutNotification))
		m_notifications.insert(pReactor->m_pTimeoutNotification.get());
}

bool SockNotifier::hasObservers() const
{
	return m_notifiCenter.hasObservers();
}

std::size_t SockNotifier::countObservers() const
{
	return m_notifiCenter.countObservers();
}

bool SockNotifier::hasObserver(const Poco::AbstractObserver& observer) const
{
    Poco::Mutex::ScopedLock lock(m_obsMutex);
    for (ObserverList::const_iterator it = m_observers.begin(); it != m_observers.end(); ++it)
    {
        if (observer.equals(**it))
        {
            return true;
        }
    }

    return false;
}

SockNotification* SockNotifier::clone(SockNotification* pNotification)
{
    SockNotification* pNf;
    if (dynamic_cast<ReadableNotification*>(pNotification))
    {
        pNf = new ReadableNotification(&pNotification->source());
    }
    else if (dynamic_cast<WritableNotification*>(pNotification))
    {
        pNf = new WritableNotification(&pNotification->source());
    }
    else if (dynamic_cast<ErrorNotification*>(pNotification))
    {
        pNf = new ErrorNotification(&pNotification->source());
    }
    else if (dynamic_cast<TimeoutNotification*>(pNotification))
    {
        pNf = new TimeoutNotification(&pNotification->source());
    }
    else if (dynamic_cast<IdleNotification*>(pNotification))
    {
        pNf = new IdleNotification(&pNotification->source());
    }
    else
    {
        pNf = new ShutdownNotification(&pNotification->source());
    }

    return pNf;
}

END_CXX_NAMESPACE_DEFINITION
