// connector pattern use in thrMgr
// andycai.sc@gmail.com 2013-04-07
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#ifndef SOCKCONNECTOR_H_INCLUDED
#define SOCKCONNECTOR_H_INCLUDED

#include "Poco/Net/Net.h"
#include "Poco/Net/ServerSocket.h"
#include "Poco/Net/StreamSocket.h"
#include "Poco/Observer.h"
#include "NameSpaceDefine.h"
#include ADD_QUOTE(INC_NAME_HEADER(NAMESPACE_NAME, ThreadManager.h))
#include ADD_QUOTE(INC_NAME_HEADER(NAMESPACE_NAME, SockNotification.h))

BEGIN_CXX_NAMESPACE_DEFINITION

template <class ServiceHandler>
class SockConnector
{
public:
	explicit SockConnector(Poco::Net::SocketAddress& address):
		m_thrManager(0)
	{
		m_socket.connectNB(address);
	}

	SockConnector(Poco::Net::SocketAddress& address, ThreadManager& thrMgr):
		m_thrManager(0)
	{
		m_socket.connectNB(address);
		registerConnector(thrMgr);
	}

	virtual ~SockConnector()
	{
		unregisterConnector();
	}

	virtual void registerConnector(ThreadManager& thrMgr)
	{
		m_thrManager = &thrMgr;
		m_thrManager->addEventHandler(m_socket, Poco::Observer<SockConnector, ReadableNotification>(*this, &SockConnector::onReadable), ThreadManager::MANUSUSRES);
		m_thrManager->addEventHandler(m_socket, Poco::Observer<SockConnector, WritableNotification>(*this, &SockConnector::onWritable), ThreadManager::MANUSUSRES);
		m_thrManager->addEventHandler(m_socket, Poco::Observer<SockConnector, ErrorNotification>(*this, &SockConnector::onError), ThreadManager::MANUSUSRES);
	}

	virtual void unregisterConnector()
	{
		if (m_thrManager)
		{
			m_thrManager->removeEventHandler(m_socket, Poco::Observer<SockConnector, ReadableNotification>(*this, &SockConnector::onReadable), ThreadManager::MANUSUSRES);
			m_thrManager->removeEventHandler(m_socket, Poco::Observer<SockConnector, WritableNotification>(*this, &SockConnector::onWritable), ThreadManager::MANUSUSRES);
			m_thrManager->removeEventHandler(m_socket, Poco::Observer<SockConnector, ErrorNotification>(*this, &SockConnector::onError), ThreadManager::MANUSUSRES);
		}
	}

	void onReadable(ReadableNotification* pNotification)
	{
		pNotification->release();
		int err = m_socket.impl()->socketError();
		if (err)
		{
			onError(err);
			unregisterConnector();
		}
		else
		{
			onConnect();
		}
	}

	void onWritable(WritableNotification* pNotification)
	{
		pNotification->release();
		onConnect();
	}

	void onConnect()
	{
		m_socket.setBlocking(true);
		createServiceHandler();
		unregisterConnector();
	}

	void onError(ErrorNotification* pNotification)
	{
		pNotification->release();
		onError(m_socket.impl()->socketError());
		unregisterConnector();
	}

protected:
	virtual ServiceHandler* createServiceHandler()
	{
		return new ServiceHandler(m_socket, *m_thrManager);
	}

	virtual void onError(int errorCode)
	{
	}

	ThreadManager* thrMgr()
	{
		return m_thrManager;
	}

	Poco::Net::Socket& socket()
	{
		return m_socket;
	}

private:
	SockConnector();
	SockConnector(const SockConnector&);
	SockConnector& operator = (const SockConnector&);

	Poco::Net::StreamSocket m_socket;
	ThreadManager* m_thrManager;
};

END_CXX_NAMESPACE_DEFINITION

#endif // SOCKCONNECTOR_H_INCLUDED
