// define common SockReactor frame can use in leader followers thread
// andycai.sc@gmail.com 2013-03-07
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

#ifndef SockReactor_H
#define SockReactor_H

#include <map>
#include "Poco/Net/Net.h"
#include "Poco/Net/Socket.h"
#include "Poco/Runnable.h"
#include "Poco/Timespan.h"
#include "Poco/Observer.h"
#include "Poco/AutoPtr.h"

#include "NameSpaceDefine.h"

BEGIN_CXX_NAMESPACE_DEFINITION

class SockNotification;
class SockNotifier;
class ThreadManager;

class DYNAMIC_LIB SockReactor
{
public:
	SockReactor();
	explicit SockReactor(const Poco::Timespan& timeout);

	virtual ~SockReactor();

	void setTimeout(const Poco::Timespan& timeout);


	const Poco::Timespan& getTimeout() const;


	void addEventHandler(const Poco::Net::Socket& socket, const Poco::AbstractObserver& observer);

	void removeEventHandler(const Poco::Net::Socket& socket, const Poco::AbstractObserver& observer);

	void handleEvents();

	static SockReactor& instance();

protected:
	virtual void onTimeout();

	virtual void onIdle();

	virtual void onShutdown();

	void dispatch(const Poco::Net::Socket& socket, SockNotification* pNotification);

	void dispatch(SockNotification* pNotification);

	void suspendEventHandler(const Poco::Net::Socket& socket, const Poco::AbstractObserver& observer);

	void resumeEventHandler(const Poco::Net::Socket& socket, const Poco::AbstractObserver& observer);

private:
	typedef Poco::AutoPtr<SockNotifier> NotifierPtr;
	typedef Poco::AutoPtr<SockNotification> NotificationPtr;
	typedef std::map<Poco::Net::Socket, NotifierPtr> EventHandlerMap;

	enum
	{
		DEFAULT_TIMEOUT = 250000
	};


	Poco::Timespan	m_timeout;

	EventHandlerMap	m_eventHandlers;
	Poco::FastMutex m_eventHMutex;

	NotificationPtr	m_pReadableNotification;
	NotificationPtr m_pWritableNotification;
	NotificationPtr m_pErrorNotification;
	NotificationPtr m_pTimeoutNotification;
	NotificationPtr m_pIdleNotification;
	NotificationPtr m_pShutdownNotification;

	Poco::Net::Socket::SocketList m_readableSockets;
	Poco::Net::Socket::SocketList m_writeableSockets;
	Poco::Net::Socket::SocketList m_exceptSockets;

    static SockReactor _sockReactor;

	friend class SockNotifier;
	friend class ThreadManager;
};

END_CXX_NAMESPACE_DEFINITION

#endif
